Dev
stuvusIT/nginx pull request #2
Opened 2017-04-11 18:00 UTC by Scriptkiddi

Working nginx suckaaaaas

2017-04-12 18:14 UTC, SlothOfAnarchy requested changes

2017-04-12 18:14 UTC, SlothOfAnarchy commented on README.md
> +```yml
remove empty chapter

2017-04-12 18:14 UTC, SlothOfAnarchy commented on README.md
> +domain_preffixe:
typo in `preffixe`
Also, you use `prefixes` below

2017-04-12 18:14 UTC, SlothOfAnarchy commented on meta/main.yml
> +  github_branch: master
remove

2017-04-12 18:14 UTC, SlothOfAnarchy commented on tasks/main.yml
> +- name: Update repositories cache and install "nginx" package
update cache missing

2017-04-12 18:14 UTC, SlothOfAnarchy commented on templates/nginx.conf.j2
> +        {%- for suffix in domain_suffixes | default(['']) -%}{#- append all domain suffixes -#}
please indent

2017-04-13 10:11 UTC, Scriptkiddi commented on README.md
> +```yml
done

2017-04-13 10:12 UTC, Scriptkiddi commented on README.md
> +domain_preffixe:
done

2017-04-13 10:12 UTC, Scriptkiddi commented on meta/main.yml
> +  github_branch: master
done

2017-04-13 10:59 UTC, SlothOfAnarchy commented on README.md
> +domain_prefixes:
are you using the changed vars correctly?

2017-04-13 11:04 UTC, SlothOfAnarchy approved these changes

2017-04-13 11:05 UTC, merged