Use external conf to block IP addresses
stuvusIT/nginx pull request #60
Opened 2020-02-28 14:10 UTC by AdriaanNiess

I've added another external config file to nginx to keep track of blocked IP addresses. This part of the configuration is going to be dynamically changed by e.g. fail2ban and acts similar to a database. So I think it makes sense to keep it seperate from the default nginx.conf.

2020-02-28 14:13 UTC, SlothOfAnarchy commented on tasks/main.yml
> +    validate: grep -v include %s | /usr/sbin/nginx -t -c /dev/stdin # Validate conf without includes
Why? the syntax should be correct nonetheless

2020-02-28 14:19 UTC, SlothOfAnarchy requested changes

2020-02-28 14:19 UTC, SlothOfAnarchy commented on templates/nginx.conf.j2
> +    include conf.d/deny.conf;
```suggestion
    include /etc/nginx/conf.d/deny.conf;
```

2020-02-28 14:23 UTC, SlothOfAnarchy approved these changes

2020-02-28 14:23 UTC, merged

2020-02-28 14:36 UTC, AdriaanNiess commented
Thx

2020-02-29 13:50 UTC, dasJ commented on tasks/main.yml
> +    validate: validate: /usr/sbin/nginx -t -c %s
Ääääähhhhhhh

2020-02-29 14:32 UTC, SlothOfAnarchy commented on tasks/main.yml
> +    validate: validate: /usr/sbin/nginx -t -c %s
> Ääääähhhhhhh

https://github.com/stuvusIT/nginx/pull/61#pullrequestreview-366439784